#define EOF_Sym	0	/* EOF */
#define identifierSym	1	/* identifier */
#define numberSym	2	/* number */
#define hexnumberSym	3	/* hexnumber */
#define stringD1Sym	4	/* string1 */
#define charD1Sym	5	/* char1 */
#define librarySym	6	/* library */
#define useSym	7	/* "use" */
#define SemicolonSym	8	/* ";" */
#define loadSym	9	/* "load" */
#define inheritSym	10	/* "inherit" */
#define LessSym	11	/* "<" */
#define classSym	12	/* "class" */
#define LbraceSym	13	/* "{" */
#define RbraceSym	14	/* "}" */
#define staticSym	15	/* "static" */
#define mySym	16	/* "my" */
#define functionSym	17	/* "function" */
#define varSym	18	/* "var" */
#define mixedSym	19	/* "mixed" */
#define shortSym	20	/* "short" */
#define intSym	21	/* "int" */
#define longSym	22	/* "long" */
#define floatSym	23	/* "float" */
#define unsignedSym	24	/* "unsigned" */
#define charSym	25	/* "char" */
#define doubleSym	26	/* "double" */
#define voidSym	27	/* "void" */
#define stringSym	28	/* "string" */
#define EqualSym	29	/* "=" */
#define CommaSym	30	/* "," */
#define LbrackSym	31	/* "[" */
#define RbrackSym	32	/* "]" */
#define LparenSym	33	/* "(" */
#define RparenSym	34	/* ")" */
#define StarSym	35	/* "*" */
#define caseSym	36	/* "case" */
#define ColonSym	37	/* ":" */
#define defaultSym	38	/* "default" */
#define breakSym	39	/* "break" */
#define continueSym	40	/* "continue" */
#define doSym	41	/* "do" */
#define whileSym	42	/* "while" */
#define forSym	43	/* "for" */
#define ifSym	44	/* "if" */
#define elseSym	45	/* "else" */
#define returnSym	46	/* "return" */
#define switchSym	47	/* "switch" */
#define BarBarSym	48	/* "||" */
#define AndAndSym	49	/* "&&" */
#define BarSym	50	/* "|" */
#define UparrowSym	51	/* "^" */
#define AndSym	52	/* "&" */
#define EqualEqualSym	53	/* "==" */
#define BangEqualSym	54	/* "!=" */
#define GreaterSym	55	/* ">" */
#define LessEqualSym	56	/* "<=" */
#define GreaterEqualSym	57	/* ">=" */
#define LessLessSym	58	/* "<<" */
#define GreaterGreaterSym	59	/* ">>" */
#define PlusSym	60	/* "+" */
#define MinusSym	61	/* "-" */
#define SlashSym	62	/* "/" */
#define PercentSym	63	/* "%" */
#define PlusPlusSym	64	/* "++" */
#define MinusMinusSym	65	/* "--" */
#define PointSym	66	/* "." */
#define MinusGreaterSym	67	/* "->" */
#define ColonColonSym	68	/* "::" */
#define newSym	69	/* "new" */
#define DollarSym	70	/* "$" */
#define StarEqualSym	71	/* "*=" */
#define SlashEqualSym	72	/* "/=" */
#define PercentEqualSym	73	/* "%=" */
#define PlusEqualSym	74	/* "+=" */
#define MinusEqualSym	75	/* "-=" */
#define AndEqualSym	76	/* "&=" */
#define UparrowEqualSym	77	/* "^=" */
#define BarEqualSym	78	/* "|=" */
#define LessLessEqualSym	79	/* "<<=" */
#define GreaterGreaterEqualSym	80	/* ">>=" */
#define BangSym	81	/* "!" */
#define TildeSym	82	/* "~" */
#define No_Sym	83	/* not */
#define PreProcessorSym	84	/* PreProcessor */
#define MAXT	No_Sym	/* Max Terminals */
