#define EOF_Sym	0	/* EOF */
#define identifierSym	1	/* identifier */
#define numberSym	2	/* number */
#define hexnumberSym	3	/* hexnumber */
#define stringD1Sym	4	/* string1 */
#define charD1Sym	5	/* char1 */
#define librarySym	6	/* library */
#define useSym	7	/* "use" */
#define SemicolonSym	8	/* ";" */
#define loadSym	9	/* "load" */
#define packageSym	10	/* "package" */
#define SlashSym	11	/* "/" */
#define inheritSym	12	/* "inherit" */
#define LessSym	13	/* "<" */
#define classSym	14	/* "class" */
#define LbraceSym	15	/* "{" */
#define RbraceSym	16	/* "}" */
#define staticSym	17	/* "static" */
#define mySym	18	/* "my" */
#define functionSym	19	/* "function" */
#define varSym	20	/* "var" */
#define mixedSym	21	/* "mixed" */
#define shortSym	22	/* "short" */
#define intSym	23	/* "int" */
#define longSym	24	/* "long" */
#define floatSym	25	/* "float" */
#define unsignedSym	26	/* "unsigned" */
#define charSym	27	/* "char" */
#define doubleSym	28	/* "double" */
#define voidSym	29	/* "void" */
#define stringSym	30	/* "string" */
#define EqualSym	31	/* "=" */
#define CommaSym	32	/* "," */
#define LbrackSym	33	/* "[" */
#define RbrackSym	34	/* "]" */
#define LparenSym	35	/* "(" */
#define RparenSym	36	/* ")" */
#define StarSym	37	/* "*" */
#define caseSym	38	/* "case" */
#define ColonSym	39	/* ":" */
#define defaultSym	40	/* "default" */
#define breakSym	41	/* "break" */
#define continueSym	42	/* "continue" */
#define doSym	43	/* "do" */
#define whileSym	44	/* "while" */
#define forSym	45	/* "for" */
#define ifSym	46	/* "if" */
#define elseSym	47	/* "else" */
#define returnSym	48	/* "return" */
#define switchSym	49	/* "switch" */
#define BarBarSym	50	/* "||" */
#define AndAndSym	51	/* "&&" */
#define BarSym	52	/* "|" */
#define UparrowSym	53	/* "^" */
#define AndSym	54	/* "&" */
#define EqualEqualSym	55	/* "==" */
#define BangEqualSym	56	/* "!=" */
#define GreaterSym	57	/* ">" */
#define LessEqualSym	58	/* "<=" */
#define GreaterEqualSym	59	/* ">=" */
#define LessLessSym	60	/* "<<" */
#define GreaterGreaterSym	61	/* ">>" */
#define PlusSym	62	/* "+" */
#define MinusSym	63	/* "-" */
#define PercentSym	64	/* "%" */
#define PlusPlusSym	65	/* "++" */
#define MinusMinusSym	66	/* "--" */
#define PointSym	67	/* "." */
#define MinusGreaterSym	68	/* "->" */
#define ColonColonSym	69	/* "::" */
#define HashHashSym	70	/* "##" */
#define newSym	71	/* "new" */
#define DollarSym	72	/* "$" */
#define StarEqualSym	73	/* "*=" */
#define SlashEqualSym	74	/* "/=" */
#define PercentEqualSym	75	/* "%=" */
#define PlusEqualSym	76	/* "+=" */
#define MinusEqualSym	77	/* "-=" */
#define AndEqualSym	78	/* "&=" */
#define UparrowEqualSym	79	/* "^=" */
#define BarEqualSym	80	/* "|=" */
#define LessLessEqualSym	81	/* "<<=" */
#define GreaterGreaterEqualSym	82	/* ">>=" */
#define BangSym	83	/* "!" */
#define TildeSym	84	/* "~" */
#define No_Sym	85	/* not */
#define PreProcessorSym	86	/* PreProcessor */
#define MAXT	No_Sym	/* Max Terminals */
