#define EOF_Sym	0	/* EOF */
#define identifierSym	1	/* identifier */
#define numberSym	2	/* number */
#define hexnumberSym	3	/* hexnumber */
#define stringD1Sym	4	/* string1 */
#define charD1Sym	5	/* char1 */
#define librarySym	6	/* library */
#define useSym	7	/* "use" */
#define SemicolonSym	8	/* ";" */
#define loadSym	9	/* "load" */
#define EqualSym	10	/* "=" */
#define inheritSym	11	/* "inherit" */
#define LessSym	12	/* "<" */
#define classSym	13	/* "class" */
#define LbraceSym	14	/* "{" */
#define RbraceSym	15	/* "}" */
#define staticSym	16	/* "static" */
#define mySym	17	/* "my" */
#define functionSym	18	/* "function" */
#define varSym	19	/* "var" */
#define mixedSym	20	/* "mixed" */
#define shortSym	21	/* "short" */
#define intSym	22	/* "int" */
#define longSym	23	/* "long" */
#define floatSym	24	/* "float" */
#define unsignedSym	25	/* "unsigned" */
#define charSym	26	/* "char" */
#define doubleSym	27	/* "double" */
#define voidSym	28	/* "void" */
#define stringSym	29	/* "string" */
#define CommaSym	30	/* "," */
#define LbrackSym	31	/* "[" */
#define RbrackSym	32	/* "]" */
#define LparenSym	33	/* "(" */
#define RparenSym	34	/* ")" */
#define StarSym	35	/* "*" */
#define caseSym	36	/* "case" */
#define ColonSym	37	/* ":" */
#define defaultSym	38	/* "default" */
#define breakSym	39	/* "break" */
#define continueSym	40	/* "continue" */
#define doSym	41	/* "do" */
#define whileSym	42	/* "while" */
#define forSym	43	/* "for" */
#define ifSym	44	/* "if" */
#define elseSym	45	/* "else" */
#define returnSym	46	/* "return" */
#define switchSym	47	/* "switch" */
#define BarBarSym	48	/* "||" */
#define AndAndSym	49	/* "&&" */
#define BarSym	50	/* "|" */
#define UparrowSym	51	/* "^" */
#define AndSym	52	/* "&" */
#define EqualEqualSym	53	/* "==" */
#define BangEqualSym	54	/* "!=" */
#define GreaterSym	55	/* ">" */
#define LessEqualSym	56	/* "<=" */
#define GreaterEqualSym	57	/* ">=" */
#define LessLessSym	58	/* "<<" */
#define GreaterGreaterSym	59	/* ">>" */
#define PlusSym	60	/* "+" */
#define MinusSym	61	/* "-" */
#define SlashSym	62	/* "/" */
#define PercentSym	63	/* "%" */
#define PlusPlusSym	64	/* "++" */
#define MinusMinusSym	65	/* "--" */
#define PointSym	66	/* "." */
#define MinusGreaterSym	67	/* "->" */
#define ColonColonSym	68	/* "::" */
#define newSym	69	/* "new" */
#define DollarSym	70	/* "$" */
#define DollarLbraceSym	71	/* "${" */
#define StarEqualSym	72	/* "*=" */
#define SlashEqualSym	73	/* "/=" */
#define PercentEqualSym	74	/* "%=" */
#define PlusEqualSym	75	/* "+=" */
#define MinusEqualSym	76	/* "-=" */
#define AndEqualSym	77	/* "&=" */
#define UparrowEqualSym	78	/* "^=" */
#define BarEqualSym	79	/* "|=" */
#define LessLessEqualSym	80	/* "<<=" */
#define GreaterGreaterEqualSym	81	/* ">>=" */
#define BangSym	82	/* "!" */
#define TildeSym	83	/* "~" */
#define No_Sym	84	/* not */
#define PreProcessorSym	85	/* PreProcessor */
#define MAXT	No_Sym	/* Max Terminals */
